#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
  path: /
  controller: App\Controller\GeneralPuroposeController

nft:
  path: /api
  controller: App\Controller\NftController